### ISSUE TITLE
Fill rate calculation on geo export doesn't make sense

### ISSUE THREAD

**Issue by JasonBarnabe** [readthedocs/ethical-ad-server#960]
Exporting the geo report to CSV, I see the following issues:

1. Some countries with 0 views show 100 fill rate, while others show 0.
2. Some countries with very few views show a fill rate that's not mathematically possible. For example, I see GI with 3 views and a 96.2 fill rate, and SC with 60 views and 99.1 fill rate.

**Comment by davidfischer** [comment]
I think there's a misunderstanding of what fill rate is. This is the % of traffic that gets a paid ad vs an unpaid ad. When we do not sell ads for a given country and never serve an unpaid ad there, it should be zero. However, in those countries there can be many requests for ads all of which are not filled. In addition, a request for an ad that is not filled does not count as a "view".

> Some countries with very few views show a fill rate that's not mathematically possible. For example, I see GI with 3 views and a 96.2 fill rate, and SC with 60 views and 99.1 fill rate.

I will investigate this. What timeframe are you looking at?

**Comment by JasonBarnabe** [comment]
> I think there's a misunderstanding of what fill rate is. This is the % of traffic that gets a paid ad vs an unpaid ad. When we do not sell ads for a given country and never serve an unpaid ad there, it should be zero. However, in those countries there can be many requests for ads all of which are not filled. In addition, a request for an ad that is not filled does not count as a "view".

For this issue, I'm specifically asking why one country with 0 views has 100 fill rate, while another country with 0 views has 0 fill rate. I'm to understand the distinction is that the 0 views/0 fill rate are countries where you never sell ads, while 0 views/100 fill rate are countries where you do sell ads, but I just didn't happen to get any traffic from those countries in the time period?

> What timeframe are you looking at?

Right now I'm looking at publish ID greasyfork, 2024-12-01 to 2024-12-12, and get these odd results:

``
GI	1	0	93.48
T1	8	0	31.79
KN	9	0	46.43
```

**Comment by davidfischer** [comment]
Thanks for the specifics. I'll dig into the data on Monday.

T1 for reference is the Tor network. We have never sold Tor-targeted paid ads to date. Usually we serve the appropriate ads to people using Tor based on the country of the exit node. So a Tor exit node in the US will be served the appropriate ads for somebody geo-targeted in the US. Then those ads will never be billed to advertisers or count as "viewed". Weird edge cases can arise when somebody requests an ad not connected to Tor and by the time the ad is filled/clicked/viewed they are not using Tor or vice versa.

**Comment by davidfischer** [comment]
I did investigate this and I'm trying to make this more obvious in the report. However, ad views (pageviews aren't a metric for us) is neither the numerator nor denominator in fill rate. Fill rate is a metric that is: (# of times we responded with a paid-eligible ad) / (# of times an ad was requested). We call the first metric an "offer" and the denominator metric a "decision". Decision is an industry-standard term.

Ad views are a subset of offers as there are many situations where a paid-eligible ad is not viewed such as the user closed their browser or navigated away. We don't show a different "view" metric to advertisers and publishers. If we show an ad view for a paid-eligible ad, that means the advertiser will pay for it and the publisher will be paid for it.

There is a very small set of regions (Russia, China, NK, a few others) where we don't even field ad requests from at all because we never have paid ads there and don't think showing house ads will result in increased business. These generally won't even show up in the report.

**Comment by davidfischer** [comment]
While making modifications to put the revenue on the geo report, you may notice that the fill rate calculation is a little different than before. It uses a much more expensive query that should give more accurate results. Previously, it used unpaid ads as a fast proxy for offers (# of times we respond with a paid-eligible ad is just the total minus the unpaid ads). Now it just scans everything.
